import React from "react";

const MyAccount = () => {
  return (
    <>
      <h1>my account1</h1>
      <h1>my account2</h1>
      <h1>my account3</h1>
      <h1>my account4</h1>
      <h1>my account5</h1>
      <h1>my account6</h1>
      <h1>my account7</h1>
      <h1>my account8</h1>
      <h1>my account9</h1>
      <h1>my account0</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
      <h1>my account</h1>
    </>
  );
};

export default MyAccount;
